from pymongo import MongoClient, ASCENDING, DESCENDING
from pymongo.errors import ConnectionFailure, DuplicateKeyError
from datetime import datetime, timedelta
from bson import ObjectId
import os

client = None
db     = None

def connect_db():
    """Initialize MongoDB connection."""
    global client, db
    mongodb_uri = os.getenv('MONGODB_URI')
    db_name = os.getenv('MONGODB_DB', 'cleansky_db')

    if not mongodb_uri:
        raise ValueError("MONGODB_URI is not set. Add it to backend/.env")

    try:
        client = MongoClient(mongodb_uri, serverSelectionTimeoutMS=5000)
        client.admin.command('ping')  # Test connection
        db = client[db_name]
        print(f"✅ MongoDB connected! Database: {db_name}")
        _create_indexes()
        return db
    except ConnectionFailure as e:
        print(f"❌ MongoDB connection failed: {e}")
        raise

def get_db():
    """Get database instance."""
    global db
    if db is None:
        connect_db()
    return db


# Create Indexes for faster queries 
def _create_indexes():
    """Create indexes matching our ER diagram relationships."""
    try:
        # aqi_data: query by location + datetime
        db.aqi_data.create_index([('location', ASCENDING), ('datetime', DESCENDING)])
        db.aqi_data.create_index([('datetime', DESCENDING)])

        # forecasts: query by location + forecast_time
        db.forecasts.create_index([('location', ASCENDING), ('forecast_time', DESCENDING)])
        db.forecasts.create_index([('user_id', ASCENDING)])

        # users: unique email
        db.users.create_index([('email', ASCENDING)], unique=True)

        # alerts: query by user + sent_time
        db.alerts.create_index([('user_id', ASCENDING), ('sent_time', DESCENDING)])
        db.alerts.create_index([('forecast_id', ASCENDING)])

        # models: query by model_name
        db.models.create_index([('model_name', ASCENDING)])

        print("✅ MongoDB indexes created!")
    except Exception as e:
        print(f"⚠️ Index creation warning: {e}")


# AQI Data Operations 
def save_aqi_reading(location: str, pollution_data: dict, predicted_aqi: float) -> str:
    """
    Save raw AQI reading to aqi_data collection.
    Called after fetching from OpenWeatherMap.
    Matches ER: AQI_Data entity.
    """
    doc = {
        'location':   location,
        'datetime':   datetime.utcnow(),
        'pm25':       pollution_data.get('PM2.5', 0),
        'pm10':       pollution_data.get('PM10', 0),
        'no2':        pollution_data.get('NO2', 0),
        'co':         pollution_data.get('CO', 0),
        'so2':        pollution_data.get('SO2', 0),
        'o3':         pollution_data.get('O3', 0),
        'nh3':        pollution_data.get('NH3', 0),
        'temperature': pollution_data.get('temperature', None),
        'humidity':    pollution_data.get('humidity', None),
        'aqi':         predicted_aqi,
        'source':      'openweathermap'
    }
    result = get_db().aqi_data.insert_one(doc)
    return str(result.inserted_id)


def get_recent_aqi(location: str, limit: int = 24) -> list:
    """Get recent AQI readings for a location (last N hours)."""
    docs = get_db().aqi_data.find(
        {'location': location},
        {'_id': 0}
    ).sort('datetime', DESCENDING).limit(limit)
    return list(docs)


def get_aqi_history(location: str, days: int = 7) -> list:
    """Get AQI history for past N days for trend charts."""
    since = datetime.utcnow() - timedelta(days=days)
    docs = get_db().aqi_data.find(
        {'location': location, 'datetime': {'$gte': since}},
        {'_id': 0}
    ).sort('datetime', ASCENDING)
    return list(docs)


# Forecast Operations 
def save_forecast(location: str, predictions: list,
                  summary: dict, data_id: str = None,
                  user_id: str = None) -> str:
    """
    Save 48hr forecast to forecasts collection.
    Matches ER: Forecast entity (generated by AQI_Data, requested by User).
    """
    doc = {
        'location':        location,
        'forecast_time':   datetime.utcnow(),
        'predictions':     predictions,
        'predicted_aqi':   summary.get('avg_aqi', 0),
        'risk_level':      _aqi_to_risk(summary.get('avg_aqi', 0)),
        'confidence_score': _calculate_confidence(predictions),
        'summary':         summary,
        'data_id':         data_id,
        'user_id':         user_id,
        'model_type':      'XGBoostRegressor'
    }
    result = get_db().forecasts.insert_one(doc)
    return str(result.inserted_id)


def get_latest_forecast(location: str) -> dict:
    """Get the most recent forecast for a location."""
    doc = get_db().forecasts.find_one(
        {'location': location},
        {'_id': 0},
        sort=[('forecast_time', DESCENDING)]
    )
    return doc


# User Operations 
def create_user(name: str, email: str,
                hashed_password: str, phone: str = None) -> str:
    """
    Create new user account.
    Matches ER: User entity.
    """
    doc = {
        'name':            name,
        'email':           email,
        'password':        hashed_password,
        'phone':           phone,
        'alert_threshold': 150,   # default AQI threshold
        'preferences': {
            'city':          'Delhi',
            'notifications': True
        },
        'created_at': datetime.utcnow()
    }
    try:
        result = get_db().users.insert_one(doc)
        return str(result.inserted_id)
    except DuplicateKeyError:
        raise ValueError(f"Email '{email}' already registered")


def get_user_by_email(email: str) -> dict:
    """Get user by email for login."""
    return get_db().users.find_one({'email': email})


def get_user_by_id(user_id: str) -> dict:
    """Get user by ID."""
    return get_db().users.find_one({'_id': ObjectId(user_id)})


def update_user_preferences(user_id: str, preferences: dict) -> bool:
    """Update user alert threshold and city preferences."""
    result = get_db().users.update_one(
        {'_id': ObjectId(user_id)},
        {'$set': {
            'alert_threshold':        preferences.get('alert_threshold', 150),
            'preferences.city':       preferences.get('city', 'Delhi'),
            'preferences.notifications': preferences.get('notifications', True)
        }}
    )
    return result.modified_count > 0


# Alert Operations 
def save_alert(user_id: str, forecast_id: str,
               city: str, aqi: float, category: str) -> str:
    """
    Save triggered alert to alerts collection.
    Matches ER: Alert entity (triggered by Forecast).
    Called when predicted AQI exceeds user's threshold.
    """
    doc = {
        'user_id':     user_id,
        'forecast_id': forecast_id,
        'alert_type':  'threshold_exceeded',
        'city':        city,
        'aqi':         aqi,
        'category':    category,
        'message':     f'AQI in {city} has reached {aqi} ({category}). Take precautions!',
        'status':      'sent',
        'sent_time':   datetime.utcnow()
    }
    result = get_db().alerts.insert_one(doc)
    return str(result.inserted_id)


def get_user_alerts(user_id: str, limit: int = 10) -> list:
    """Get recent alerts for a user."""
    docs = get_db().alerts.find(
        {'user_id': user_id},
        {'_id': 0}
    ).sort('sent_time', DESCENDING).limit(limit)
    return list(docs)


def check_and_trigger_alert(user_id: str, forecast_id: str,
                             city: str, aqi: float, category: str) -> bool:
    """
    Check if AQI exceeds user threshold and trigger alert.
    Matches sequence diagram: 'Send Alert if threshold exceeded'.
    """
    user = get_user_by_id(user_id)
    if not user:
        return False

    threshold = user.get('alert_threshold', 150)
    notifications = user.get('preferences', {}).get('notifications', True)

    if notifications and aqi >= threshold:
        save_alert(user_id, forecast_id, city, aqi, category)
        print(f"🚨 Alert triggered for user {user_id}: AQI={aqi} >= threshold={threshold}")
        return True

    return False


# Model Metadata Operations 
def save_model_metadata(model_name: str, model_type: str,
                         accuracy: float) -> str:
    """
    Save ML model metadata.
    Matches ER: Model entity.
    """
    doc = {
        'model_name':   model_name,
        'model_type':   model_type,
        'accuracy':     accuracy,
        'last_trained': datetime.utcnow()
    }
    # Update if exists, insert if not
    result = get_db().models.update_one(
        {'model_name': model_name},
        {'$set': doc},
        upsert=True
    )
    return str(result.upserted_id or 'updated')


def get_model_metadata(model_name: str = 'XGBoost AQI v1') -> dict:
    """Get model metadata for dashboard display."""
    return get_db().models.find_one(
        {'model_name': model_name},
        {'_id': 0}
    )


# Helper Functions 
def _aqi_to_risk(aqi: float) -> str:
    if aqi <= 50:    return 'Good'
    elif aqi <= 100: return 'Satisfactory'
    elif aqi <= 200: return 'Moderate'
    elif aqi <= 300: return 'Poor'
    elif aqi <= 400: return 'Very Poor'
    else:            return 'Severe'


def _calculate_confidence(predictions: list) -> float:
    """
    Calculate confidence score based on prediction consistency.
    More consistent predictions = higher confidence.
    """
    if not predictions:
        return 0.0
    aqi_values = [p.get('aqi', 0) for p in predictions]
    if not aqi_values:
        return 0.0
    mean = sum(aqi_values) / len(aqi_values)
    variance = sum((x - mean) ** 2 for x in aqi_values) / len(aqi_values)
    # Lower variance = higher confidence
    confidence = max(0.5, min(0.99, 1 - (variance / 10000)))
    return round(confidence, 2)