"use client";

import { useEffect, useState } from "react";
import { useCity } from "@/context/CityContext";
import { fetchPollutants } from "@/lib/api";
import type { PollutantDetail } from "@/lib/types";
import GlassCard from "@/components/GlassCard";
import { DashboardSkeleton } from "@/components/LoadingSkeleton";
import { motion } from "framer-motion";
import {
  AlertTriangle,
  Factory,
  Car,
  HeartPulse,
  CircleDot,
} from "lucide-react";

type PollutantCopy = {
  title: string;
  description: string;
  health: string[];
};

const stagger = {
  hidden: {},
  show: { transition: { staggerChildren: 0.1 } },
};

const fadeUp = {
  hidden: { opacity: 0, y: 20 },
  show: {
    opacity: 1,
    y: 0,
    transition: { duration: 0.5, ease: [0.25, 0.46, 0.45, 0.94] as const },
  },
};

export default function PollutantsPage() {
  const { city, lat, lon } = useCity();
  const [pollutants, setPollutants] = useState<PollutantDetail[]>([]);
  const [dominantPollutant, setDominantPollutant] = useState("");
  const [activePollutant, setActivePollutant] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;

    async function load() {
      setLoading(true);
      setError(null);

      try {
        const res = await fetchPollutants(city, lat, lon);
        if (cancelled) return;
        setPollutants(res.pollutants);
        setDominantPollutant(res.dominant_pollutant);
        setActivePollutant(
          res.dominant_pollutant || res.pollutants[0]?.name || "",
        );
      } catch (e) {
        if (!cancelled)
          setError(e instanceof Error ? e.message : "Failed to load");
      } finally {
        if (!cancelled) setLoading(false);
      }
    }

    load();
    return () => {
      cancelled = true;
    };
  }, [city, lat, lon]);

  if (loading) return <DashboardSkeleton />;

  if (error) {
    return (
      <GlassCard>
        <div className="text-center py-12">
          <AlertTriangle className="w-10 h-10 text-[#F97316] mx-auto mb-4" />
          <h2 className="text-xl font-semibold text-[#E2E8F0] mb-2">
            Connection Error
          </h2>
          <p className="text-[#94A3B8]">{error}</p>
        </div>
      </GlassCard>
    );
  }

  const pollutantCopy: Record<string, PollutantCopy> = {
    "PM2.5": {
      title: "PM2.5 - Fine Particulate Matter",
      description:
        "Microscopic particles that remain suspended in air and penetrate deep into the lungs. PM2.5 is strongly linked with urban combustion sources and prolonged haze episodes.",
      health: ["Respiratory effects", "Cardiovascular effects"],
    },
    PM10: {
      title: "PM10 - Coarse Particulate Matter",
      description:
        "Larger inhalable particles generated by road dust, construction activity, and industrial emissions. PM10 contributes to airway irritation and persistent cough.",
      health: ["Airway irritation", "Reduced lung function"],
    },
    O3: {
      title: "O3 - Ground-Level Ozone",
      description:
        "A reactive gas formed when sunlight interacts with pollutants from vehicles and industry. Elevated ozone causes chest discomfort and breathing difficulty, especially during daytime peaks.",
      health: ["Lung inflammation", "Asthma trigger"],
    },
    NO2: {
      title: "NO2 - Nitrogen Dioxide",
      description:
        "Produced primarily from fuel combustion and dense traffic corridors. NO2 inflames airways and worsens pre-existing respiratory disease.",
      health: ["Bronchial irritation", "Reduced oxygen intake"],
    },
    SO2: {
      title: "SO2 - Sulfur Dioxide",
      description:
        "Common around industrial and thermal power zones where sulfur-containing fuels are burned. Short-term peaks can cause breathing discomfort and eye irritation.",
      health: ["Throat irritation", "Breathing discomfort"],
    },
    CO: {
      title: "CO - Carbon Monoxide",
      description:
        "A colorless gas from incomplete combustion in vehicles and generators. CO reduces oxygen transport in blood and may cause headaches or fatigue in exposed populations.",
      health: ["Reduced oxygen delivery", "Neurological symptoms"],
    },
  };

  const selected =
    pollutants.find((p) => p.name === activePollutant) || pollutants[0] || null;
  const selectedCopy =
    (selected && pollutantCopy[selected.name]) ||
    (selected
      ? {
          title: `${selected.name} - Pollutant Overview`,
          description:
            "This pollutant contributes to the present air quality load and should be monitored against health and guideline thresholds.",
          health: ["Respiratory effects", "Environmental stress"],
        }
      : null);

  const getSourceTracking = (pollutant?: PollutantDetail | null) => {
    if (!pollutant) return { traffic: 50, industrial: 50 };
    const pressure = Math.min(
      (pollutant.value / Math.max(pollutant.who_limit, 1)) * 100,
      100,
    );
    const traffic = Math.min(Math.max(Math.round(pressure * 0.6), 25), 80);
    return { traffic, industrial: 100 - traffic };
  };

  const sources = getSourceTracking(selected);

  return (
    <motion.div
      className="space-y-6"
      variants={stagger}
      initial="hidden"
      animate="show"
    >
      <motion.div variants={fadeUp}>
        <p className="page-kicker">Pollutant Diagnostics</p>
        <h1 className="page-title">Pollutants Intelligence</h1>
        <p className="page-subtitle mt-2">
          Live atmospheric profile for{" "}
          <span className="text-[#78EAF8]">{city}</span>
          {dominantPollutant ? (
            <>
              {" "}
              · Dominant{" "}
              <span className="text-[#F87171]">{dominantPollutant}</span>
            </>
          ) : null}
        </p>
      </motion.div>

      <motion.div
        className="grid grid-cols-1 xl:grid-cols-[280px_1fr] gap-5"
        variants={fadeUp}
      >
        <GlassCard className="p-3 md:p-4">
          <div className="space-y-2">
            {pollutants.map((item) => {
              const active = item.name === (selected?.name || "");
              return (
                <button
                  key={item.name}
                  type="button"
                  onClick={() => setActivePollutant(item.name)}
                  className={`w-full rounded-2xl border p-4 text-left transition-all duration-200 ${
                    active
                      ? "border-[#78EAF8]/60 bg-[#0B1220]/90"
                      : "border-white/5 bg-[#0B1220]/70 hover:border-[#78EAF8]/30"
                  }`}
                >
                  <div className="flex items-start gap-3">
                    <div
                      className={`mt-1 rounded-full p-2 ${
                        active ? "bg-[#78EAF8]/25" : "bg-[#1F2937]"
                      }`}
                    >
                      <CircleDot className="w-4 h-4 text-[#78EAF8]" />
                    </div>
                    <div>
                      <h3 className="text-xl font-bold text-[#E5E7EB] leading-none">
                        {item.name}
                      </h3>
                      <p className="text-xs text-[#7D8BA1] mt-2 leading-relaxed">
                        {item.status === "exceeded"
                          ? "Above WHO threshold"
                          : "Within WHO threshold"}
                      </p>
                    </div>
                  </div>
                </button>
              );
            })}
          </div>
        </GlassCard>

        <div className="space-y-5">
          <GlassCard className="p-6 md:p-7">
            {selected && selectedCopy ? (
              <>
                <h2 className="section-title text-[#E5E7EB]">
                  {selectedCopy.title}
                </h2>
                <p className="text-[#9AA6BC] text-sm md:text-base mt-4 leading-relaxed max-w-4xl">
                  {selectedCopy.description}
                </p>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mt-8">
                  <div>
                    <h3 className="section-title text-[#E5E7EB] mb-4">
                      Source Tracking
                    </h3>
                    <div className="space-y-4">
                      <div>
                        <div className="flex items-center justify-between mb-2">
                          <p className="flex items-center gap-2 text-[#CBD5E1]">
                            <Car className="w-4 h-4 text-[#78EAF8]" />
                            Traffic
                          </p>
                          <span className="text-[#CBD5E1] text-sm">
                            {sources.traffic}%
                          </span>
                        </div>
                        <div className="h-2 rounded-full bg-[#334155] overflow-hidden">
                          <div
                            className="h-full rounded-full bg-gradient-to-r from-[#60A5FA] to-[#7CE8F6]"
                            style={{ width: `${sources.traffic}%` }}
                          />
                        </div>
                      </div>
                      <div>
                        <div className="flex items-center justify-between mb-2">
                          <p className="flex items-center gap-2 text-[#CBD5E1]">
                            <Factory className="w-4 h-4 text-[#78EAF8]" />
                            Industrial
                          </p>
                          <span className="text-[#CBD5E1] text-sm">
                            {sources.industrial}%
                          </span>
                        </div>
                        <div className="h-2 rounded-full bg-[#334155] overflow-hidden">
                          <div
                            className="h-full rounded-full bg-gradient-to-r from-[#60A5FA] to-[#7CE8F6]"
                            style={{ width: `${sources.industrial}%` }}
                          />
                        </div>
                      </div>
                    </div>
                  </div>

                  <div>
                    <h3 className="section-title text-[#E5E7EB] mb-4">
                      Health Impacts
                    </h3>
                    <div className="grid grid-cols-2 gap-4">
                      {selectedCopy.health.map((impact) => (
                        <div
                          key={impact}
                          className="rounded-2xl border border-white/5 bg-[#0B1220]/70 p-4"
                        >
                          <div className="w-10 h-10 rounded-full bg-[#1F2937] grid place-items-center mb-3">
                            <HeartPulse className="w-5 h-5 text-[#78EAF8]" />
                          </div>
                          <p className="text-[#D1D5DB] text-sm leading-snug">
                            {impact}
                          </p>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              </>
            ) : (
              <div className="text-center py-8 text-[#94A3B8]">
                No pollutant data available.
              </div>
            )}
          </GlassCard>

          <GlassCard className="p-6 md:p-7">
            <h3 className="section-title text-[#E5E7EB] mb-6">
              Current Levels vs WHO Guidelines
            </h3>
            <div className="space-y-5">
              {pollutants.map((p) => {
                const ratio = Math.min(
                  (p.value / Math.max(p.who_limit, 1)) * 100,
                  100,
                );
                const exceeded = p.status === "exceeded";
                const isFocus = selected?.name === p.name;
                return (
                  <div key={p.name}>
                    <div className="grid grid-cols-[56px_1fr_auto] md:grid-cols-[70px_1fr_auto] items-center gap-3 md:gap-4">
                      <span className="text-[#CBD5E1] text-sm md:text-base font-medium">
                        {p.name}
                      </span>
                      <div className="relative">
                        <div className="h-3 rounded-full bg-[#3A4658]" />
                        <div
                          className="absolute inset-y-0 left-0 rounded-full bg-gradient-to-r from-[#63AFFF] to-[#7CE8F6]"
                          style={{ width: `${ratio}%` }}
                        />
                        {exceeded ? (
                          <div
                            className="absolute inset-y-[-4px] w-[2px] bg-[#F87171]"
                            style={{ left: `${Math.min(ratio, 98)}%` }}
                          />
                        ) : null}
                      </div>
                      <div className="text-right">
                        <p className="text-[#CBD5E1] text-sm md:text-base">
                          {p.value.toFixed(1)} {p.unit}
                        </p>
                        <p className="text-[#7D8BA1] text-xs md:text-sm">
                          WHO {p.who_limit} {p.unit}
                        </p>
                      </div>
                    </div>
                    <div className="pl-[56px] md:pl-[70px] mt-1 text-xs">
                      {exceeded ? (
                        <span className="text-[#F87171] uppercase tracking-wide font-semibold">
                          Exceeded{isFocus ? " · Focus Pollutant" : ""}
                        </span>
                      ) : (
                        <span className="text-[#7D8BA1] uppercase tracking-wide">
                          Within Limit
                        </span>
                      )}
                    </div>
                  </div>
                );
              })}
            </div>
          </GlassCard>
        </div>
      </motion.div>
    </motion.div>
  );
}
